// Exported
export default {
    id: 20,
    name: 'Suboctaver',
    category: 'Pitch',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | Active',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 1,
            number: '02',
            name: 'A | Range',
            type: 'select',
            options: [
                { id: 0, name: 'LO' },
                { id: 1, name: 'MID' },
                { id: 2, name: 'HI' },
            ],
        },
        {
            id: 2,
            number: '03',
            name: 'A | Direct',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | Octave 1',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | Octave 2',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'B | Active',
            type: 'boolean',
            style: 'onOff',
        },
        {
            id: 6,
            number: '07',
            name: 'B | Range',
            type: 'select',
            options: [
                { id: 0, name: 'LO' },
                { id: 1, name: 'MID' },
                { id: 2, name: 'HI' },
            ],
        },
        {
            id: 7,
            number: '08',
            name: 'B | Direct',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'B | Octave 1',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'B | Octave 2',
            type: 'double',
            precision: 0,
            minimum: 0,
            maximum: 100,
            unit: '%',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
