// Exported
export default {
    id: 27,
    name: 'Dual Graphic EQ',
    category: 'Equalizer',
    parameters: [
        {
            id: 0,
            number: '01',
            name: 'A | 20',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 1,
            number: '02',
            name: 'A | 25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 2,
            number: '03',
            name: 'A | 31.5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 3,
            number: '04',
            name: 'A | 40',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 4,
            number: '05',
            name: 'A | 50',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 5,
            number: '06',
            name: 'A | 63',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 6,
            number: '07',
            name: 'A | 80',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 7,
            number: '08',
            name: 'A | 100',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 8,
            number: '09',
            name: 'A | 125',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 9,
            number: '10',
            name: 'A | 160',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 10,
            number: '11',
            name: 'A | 200',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 11,
            number: '12',
            name: 'A | 250',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 12,
            number: '13',
            name: 'A | 315',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 13,
            number: '14',
            name: 'A | 400',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 14,
            number: '15',
            name: 'A | 500',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 15,
            number: '16',
            name: 'A | 630',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 16,
            number: '17',
            name: 'A | 800',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 17,
            number: '18',
            name: 'A | 1k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 18,
            number: '19',
            name: 'A | 1k25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 19,
            number: '20',
            name: 'A | 1k6',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 20,
            number: '21',
            name: 'A | 2k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 21,
            number: '22',
            name: 'A | 2k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 22,
            number: '23',
            name: 'A | 3k15',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 23,
            number: '24',
            name: 'A | 4k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 24,
            number: '25',
            name: 'A | 5k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 25,
            number: '26',
            name: 'A | 6k3',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 26,
            number: '27',
            name: 'A | 8k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 27,
            number: '28',
            name: 'A | 10k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 28,
            number: '29',
            name: 'A | 12k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 29,
            number: '30',
            name: 'A | 16k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 30,
            number: '31',
            name: 'A | 20k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 31,
            number: '32',
            name: 'A | Master',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 32,
            number: '33',
            name: 'B | 20',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 33,
            number: '34',
            name: 'B | 25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 34,
            number: '35',
            name: 'B | 31.5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 35,
            number: '36',
            name: 'B | 40',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 36,
            number: '37',
            name: 'B | 50',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 37,
            number: '38',
            name: 'B | 63',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 38,
            number: '39',
            name: 'B | 80',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 39,
            number: '40',
            name: 'B | 100',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 40,
            number: '41',
            name: 'B | 125',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 41,
            number: '42',
            name: 'B | 160',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 42,
            number: '43',
            name: 'B | 200',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 43,
            number: '44',
            name: 'B | 250',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 44,
            number: '45',
            name: 'B | 315',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 45,
            number: '46',
            name: 'B | 400',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 46,
            number: '47',
            name: 'B | 500',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 47,
            number: '48',
            name: 'B | 630',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 48,
            number: '49',
            name: 'B | 800',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 49,
            number: '50',
            name: 'B | 1k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 50,
            number: '51',
            name: 'B | 1k25',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 51,
            number: '52',
            name: 'B | 1k6',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 52,
            number: '53',
            name: 'B | 2k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 53,
            number: '54',
            name: 'B | 2k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 54,
            number: '55',
            name: 'B | 3k15',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 55,
            number: '56',
            name: 'B | 4k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 56,
            number: '57',
            name: 'B | 5k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 57,
            number: '58',
            name: 'B | 6k3',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 58,
            number: '59',
            name: 'B | 8k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 59,
            number: '60',
            name: 'B | 10k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 60,
            number: '61',
            name: 'B | 12k5',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 61,
            number: '62',
            name: 'B | 16k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 62,
            number: '63',
            name: 'B | 20k',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
        {
            id: 63,
            number: '64',
            name: 'B | Master',
            type: 'double',
            precision: 1,
            minimum: -15,
            maximum: 15,
            unit: 'dB',
            scale: 'linear',
            oscType: 'fractional',
        },
    ],
};
